[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.pipx]
uvx = true

[tools]
"aqua:jesseduffield/lazygit" = "latest"
awscli = "latest"
bun = "latest"
"cargo:cargo-compete" = "latest"
"cargo:cargo-equip" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:sqlx-cli" = "0.7.3"
"cargo:taplo-cli" = "latest"
deno = "latest"
eza = "latest"
fzf = "latest"
"github:BurntSushi/ripgrep" = "latest"
go = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
node = "24.11.0"
"npm:@biomejs/biome" = "latest"
"npm:aws-cdk" = "latest"
"npm:serverless" = "latest"
"pipx:httpie" = "latest"
"pipx:online-judge-api-client" = "latest"
pnpm = "latest"
python = "latest"
rust = "1.89.0"
rust-analyzer = "2025-11-10"
uv = "latest"

[tasks.equiq]
run = '''
cargo equip --remove docs --remove comments --minify libs --no-check ${usage_bin:+--bin "${usage_bin}"} > submit.rs
'''
usage = '''
arg "<bin>" default=""
'''
description = "equip for library checker"
alias = "eq"

[tasks.eqq]
run = '''
cargo equip --exclude ac-library-rs --exclude itertools --exclude num --exclude num-bigint --exclude num-decimal --exclude proconio  --exclude rust-decimal --exclude superslice --exclude regex --exclude num-traits --exclude regex --exclude easy-ext --remove docs --remove comments --minify libs --no-check ${usage_bin:+--bin "${usage_bin}"} > submit.rs
'''
usage = '''
arg "<bin>" default=""
'''
description = "equip for atcoder"

[tasks."compete:test"]
run = '''
cargo compete test ${usage_id}
'''
usage = '''
arg "<id>" default=""
'''
description = "cargo compete test <id>. alias: t"
alias = "t"

[tasks."compete:submit"]
run = '''
cargo compete submit ${usage_id}
'''
usage = '''
arg "<id>" default=""
'''
description = "cargo compete submit <id>. alias: s"
alias = "s"


[tasks."compete:login"]
run = '''
cargo compete login atcoder
'''
usage = '''
arg "<id>" default=""
'''
description = "cargo compete login atcoder. alias: login"
alias = "login"


