name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  chezmoi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy chezmoi config
        run: |
          mkdir -p ~/.config/chezmoi
          cat > ~/.config/chezmoi/chezmoi.toml << 'EOF'
          [data]
          cargo_atcoder_template = """
          fn main() {}
          """
          name = "name"
          email = "mail"
          brew_install = "false"
          mise_install = "false"
          neovim_install = "false"
          neovim_version = "v0.11.5"
          font_install = "false"
          apt_install = "false"
          EOF

      - name: Install chezmoi
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: chezmoi data
        run: |
          chezmoi data

      - name: dry-run
        run: |
          chezmoi apply -S . --dry-run

      - name: apply
        run: |
          chezmoi apply -S .
